// Views/TransistorListPage.xaml.cs
using DbTransistorsApp.ViewModels;
using System.Diagnostics;

namespace DbTransistorsApp.Views;

public partial class TransistorListPage : ContentPage, IQueryAttributable
{
    private readonly TransistorListViewModel _viewModel;

    public TransistorListPage(TransistorListViewModel viewModel)
    {
        InitializeComponent();
        _viewModel = viewModel;
        BindingContext = _viewModel;
    }

    // InitializeComponent is generated by XAML source generator at build time.

    protected override async void OnAppearing()
    {
        base.OnAppearing();

        // Intentamos cargar si el ViewModel ya fue inicializado
        if (BindingContext is TransistorListViewModel vm)
        {
            await vm.OnAppearingAsync();
        }
    }

    protected override async void OnDisappearing()
    {
        base.OnDisappearing();
        await _viewModel.OnDisappearingAsync();
    }

    // Recibir parámetros de navegación cuando se usa Shell GoToAsync con parámetros
    public void ApplyQueryAttributes(IDictionary<string, object> query)
    {
        try
        {
            if (BindingContext is TransistorListViewModel vm)
            {
                // Buscar TableType en mayúsculas o minúsculas
                if (query.TryGetValue("TableType", out var tableObj) || query.TryGetValue("tableType", out tableObj))
                {
                    var s = tableObj?.ToString();
                    Debug.WriteLine($"TransistorListPage.ApplyQueryAttributes: TableType={s}");
                    if (!string.IsNullOrEmpty(s) && Enum.TryParse<TableType>(s, true, out var tt))
                    {
                        _ = MainThread.InvokeOnMainThreadAsync(async () => await vm.InitializeAsync(tt));
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"ApplyQueryAttributes error: {ex}");
        }
    }
}
