// Views/TransistorListPage.xaml.cs
using DbTransistorsApp.Helpers;
using DbTransistorsApp.ViewModels;
using System.Diagnostics;

namespace DbTransistorsApp.Views;

public partial class TransistorListPage : ContentPage, IQueryAttributable
{
    private readonly TransistorListViewModel _viewModel;
        private bool _headerBuilt = false;
        private bool _templateBuilt = false;

    public TransistorListPage(TransistorListViewModel viewModel)
    {
        InitializeComponent();
        _viewModel = viewModel;
        BindingContext = _viewModel;
    }

    // InitializeComponent is generated by XAML source generator at build time.

    
    protected override async void OnAppearing()
    {
        base.OnAppearing();

        // Intentamos cargar si el ViewModel ya fue inicializado
        if (BindingContext is TransistorListViewModel vm)
        {
            // Cargar datos (en VM puede usar background tasks)
            await vm.OnAppearingAsync();

            // Construir encabezado una vez el ViewModel tenga HeaderFields
            if (!_headerBuilt && vm.HeaderFields != null)
            {
                BuildHeader(vm);
                _headerBuilt = true;
            }

            // Construir DataTemplate dinámico una vez
            if (!_templateBuilt)
            {
                BuildItemTemplate();
                _templateBuilt = true;
            }
        }
    }
    
    /*
    protected override async void OnAppearing()
    {
        base.OnAppearing();

        if (BindingContext is TransistorListViewModel vm)
        {
            await vm.OnAppearingAsync();

            // Construir la tabla después de que los datos estén cargados
            BuildTable(vm);
        }
    }
    */
    /*
    private void BuildItemTemplate()
    {
        try
        {
            var collection = this.FindByName<CollectionView>("TransistorsCollection");
            if (collection == null) return;

            var dt = new DataTemplate(() =>
            {
                var grid = new Grid { Padding = 5 };
                grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(150) });
                grid.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Star });

                var tap = new TapGestureRecognizer();
                tap.SetBinding(TapGestureRecognizer.CommandProperty, new Binding("BindingContext.SelectTransistorCommand", source: this));
                tap.SetBinding(TapGestureRecognizer.CommandParameterProperty, new Binding("Original"));

                var nameLabel = new Label();
                nameLabel.SetBinding(Label.TextProperty, "Name");
                nameLabel.VerticalOptions = LayoutOptions.Center;
                nameLabel.WidthRequest = 150;
                grid.Add(nameLabel, 0, 0);

                var stack = new HorizontalStackLayout { Spacing = 0 };
                // agregar placeholders para MaxParameterCount celdas; cada celda bindeará a Values[i]
                int max = ColumnLayoutHelper.MaxParameterCount;
                for (int i = 0; i < max; i++)
                {
                    var border = new Border { Padding = 4, StrokeThickness = 0, BackgroundColor = Colors.Transparent };
                    var lbl = new Label { VerticalOptions = LayoutOptions.Center, HorizontalTextAlignment = TextAlignment.Center, LineBreakMode = LineBreakMode.TailTruncation };
                    // Bind to Values[i] via indexer path
                    lbl.SetBinding(Label.TextProperty, new Binding($"Values[{i}]") );
                    border.Content = lbl;
                    border.WidthRequest = ((TransistorListViewModel)BindingContext).ColumnWidth;
                    stack.Add(border);
                }

                grid.Add(stack, 1, 0);
                grid.GestureRecognizers.Add(tap);
                return grid;
            });

            collection.ItemTemplate = dt;
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"BuildItemTemplate error: {ex}");
        }
    }
    
    private void BuildHeader(TransistorListViewModel vm)
    {
        try
        {
            // Acceder al Grid nombrado HeaderArea en XAML
            var grid = this.FindByName<Grid>("HeaderArea");
            grid.ColumnDefinitions.Clear();
            grid.Children.Clear();

            // Columna fija para Nombre
            grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(150) });
            // Contenedor para parámetros
            grid.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Star });

            var lblName = new Label { Text = "Nombre", TextColor = Colors.White, FontAttributes = FontAttributes.Bold, VerticalOptions = LayoutOptions.Center };
            grid.Add(lblName, 0, 0);

            var stack = new HorizontalStackLayout { Spacing = 0 };
            for (int i = 0; i < vm.HeaderFields.Count; i++)
            {
                var frame = new Frame { Padding = 4, CornerRadius = 0, HasShadow = false, BackgroundColor = Colors.Transparent, WidthRequest = vm.ColumnWidth };
                var lbl = new Label { Text = vm.HeaderFields[i], TextColor = Colors.White, FontAttributes = FontAttributes.Bold, HorizontalTextAlignment = TextAlignment.Center, LineBreakMode = LineBreakMode.TailTruncation };
                frame.Content = lbl;
                stack.Add(frame);
            }

            grid.Add(stack, 1, 0);
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"BuildHeader error: {ex}");
        }
    }
    */
    private void BuildItemTemplate()
    {
        try
        {
            var collection = this.FindByName<CollectionView>("TransistorsCollection");
            if (collection == null) return;

            // Obtener el ViewModel
            var vm = BindingContext as TransistorListViewModel;
            if (vm == null) return;

            var dt = new DataTemplate(() =>
            {
                // 1. CREAR GRID CON 2 COLUMNAS
                var grid = new Grid
                {
                    Padding = new Thickness(5, 2, 5, 2),
                    BackgroundColor = Colors.Transparent
                };
                grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(150) }); // Nombre
                grid.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Star });    // Parámetros

                // 2. GESTURE PARA SELECCIÓN
                var tap = new TapGestureRecognizer();
                tap.SetBinding(TapGestureRecognizer.CommandProperty, new Binding("BindingContext.SelectTransistorCommand", source: this));
                tap.SetBinding(TapGestureRecognizer.CommandParameterProperty, new Binding("."));
                grid.GestureRecognizers.Add(tap);

                // 3. LABEL PARA EL NOMBRE (Columna 0)
                var nameLabel = new Label
                {
                    VerticalOptions = LayoutOptions.Center,
                    HorizontalOptions = LayoutOptions.Center,
                    FontSize = 13,
                    Padding = new Thickness(5, 6, 5, 6),
                    TextColor = Colors.Black
                };
                nameLabel.SetBinding(Label.TextProperty, "Name");
                Grid.SetColumn(nameLabel, 0);
                Grid.SetRow(nameLabel, 0);
                grid.Children.Add(nameLabel);

                // 4. STACK PARA PARÁMETROS (Columna 1)
                var stack = new HorizontalStackLayout
                {
                    Spacing = 0,
                    VerticalOptions = LayoutOptions.Center,
                    HorizontalOptions = LayoutOptions.FillAndExpand
                };

                // Obtener el máximo de parámetros
                int max = ColumnLayoutHelper.MaxParameterCount;
                for (int i = 0; i < max; i++)
                {
                    var border = new Border
                    {
                        Padding = new Thickness(4, 0),
                        StrokeThickness = 0,
                        BackgroundColor = Colors.Transparent,
                        WidthRequest = vm.ColumnWidth,
                        HeightRequest = 38,
                        HorizontalOptions = LayoutOptions.Fill
                    };

                    var lbl = new Label
                    {
                        VerticalOptions = LayoutOptions.Center,
                        HorizontalTextAlignment = TextAlignment.Center,
                        VerticalTextAlignment = TextAlignment.Center,
                        LineBreakMode = LineBreakMode.TailTruncation,
                        FontSize = 13,
                        TextColor = Colors.Black
                    };

                    // Bind a Values[i] usando el indexer
                    lbl.SetBinding(Label.TextProperty, new Binding($"Values[{i}]"));
                    border.Content = lbl;
                    stack.Children.Add(border);
                }

                Grid.SetColumn(stack, 1);
                Grid.SetRow(stack, 0);
                grid.Children.Add(stack);

                return grid;
            });

            collection.ItemTemplate = dt;
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"BuildItemTemplate error: {ex}");
        }
    }
    private void BuildHeader(TransistorListViewModel vm)
    {
        try
        {
            var grid = this.FindByName<Grid>("HeaderArea");
            if (grid == null) return;

            grid.ColumnDefinitions.Clear();
            grid.Children.Clear();

            // 1. COLUMNA FIJA PARA NOMBRE (150px)
            grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(150) });

            // 2. COLUMNA PARA PARÁMETROS (Star - ocupa el resto)
            grid.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Star });

            // 3. ENCABEZADO "NOMBRE" (Columna 0)
            var lblName = new Label
            {
                Text = "Nombre",
                TextColor = Colors.White,
                FontAttributes = FontAttributes.Bold,
                VerticalOptions = LayoutOptions.Center,
                HorizontalOptions = LayoutOptions.Center,
                Padding = new Thickness(5, 8, 5, 8)
            };
            Grid.SetColumn(lblName, 0);
            Grid.SetRow(lblName, 0);
            grid.Children.Add(lblName);

            // 4. ENCABEZADOS DE PARÁMETROS (Columna 1 - en un HorizontalStackLayout)
            var stack = new HorizontalStackLayout
            {
                Spacing = 0,
                VerticalOptions = LayoutOptions.Center,
                HorizontalOptions = LayoutOptions.FillAndExpand
            };

            for (int i = 0; i < vm.HeaderFields.Count; i++)
            {
                var border = new Border
                {
                    Padding = new Thickness(4, 0),
                    StrokeThickness = 0,
                    BackgroundColor = Colors.Transparent,
                    WidthRequest = vm.ColumnWidth,
                    HeightRequest = 40,
                    HorizontalOptions = LayoutOptions.Fill
                };

                var lbl = new Label
                {
                    Text = vm.HeaderFields[i],
                    TextColor = Colors.White,
                    FontAttributes = FontAttributes.Bold,
                    HorizontalTextAlignment = TextAlignment.Center,
                    VerticalTextAlignment = TextAlignment.Center,
                    LineBreakMode = LineBreakMode.TailTruncation
                };
                border.Content = lbl;
                stack.Children.Add(border);
            }

            // Agregar el stack a la columna 1
            Grid.SetColumn(stack, 1);
            Grid.SetRow(stack, 0);
            grid.Children.Add(stack);
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"BuildHeader error: {ex}");
        }
    }


    private void BuildTable(TransistorListViewModel vm)
    {
        try
        {
            // Construir el encabezado fijo
            BuildHeader(vm);

            // Construir el ItemTemplate del CollectionView
            BuildItemTemplate();
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"BuildTable error: {ex}");
        }
    }
    protected override async void OnDisappearing()
    {
        base.OnDisappearing();
        await _viewModel.OnDisappearingAsync();
    }

    // Recibir parámetros de navegación cuando se usa Shell GoToAsync con parámetros
    public void ApplyQueryAttributes(IDictionary<string, object> query)
    {
        try
        {
            if (BindingContext is TransistorListViewModel vm)
            {
                // Buscar TableType en mayúsculas o minúsculas
                if (query.TryGetValue("TableType", out var tableObj) || query.TryGetValue("tableType", out tableObj))
                {
                    var s = tableObj?.ToString();
                    Debug.WriteLine($"TransistorListPage.ApplyQueryAttributes: TableType={s}");
                    if (!string.IsNullOrEmpty(s) && Enum.TryParse<TableType>(s, true, out var tt))
                    {
                        _ = MainThread.InvokeOnMainThreadAsync(async () => await vm.InitializeAsync(tt));
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"ApplyQueryAttributes error: {ex}");
        }
    }


}
