// Views/TransistorEditPage.xaml.cs
using DbTransistorsApp.ViewModels;

namespace DbTransistorsApp.Views;

public partial class TransistorEditPage : ContentPage
{
    private readonly TransistorEditViewModel _viewModel;

    public TransistorEditPage(TransistorEditViewModel viewModel)
    {
        InitializeComponent();
        _viewModel = viewModel;
        BindingContext = _viewModel;
    }

    // InitializeComponent is generated by XAML source generator at build time.

    protected override async void OnAppearing()
    {
        base.OnAppearing();

        if (BindingContext is TransistorEditViewModel vm)
        {
            // Obtener parámetros de navegación
            var parameters = Shell.Current.CurrentPage?.BindingContext as TransistorEditViewModel;
            if (parameters != null)
            {
                await vm.OnAppearingAsync();
            }
        }
    }

    protected override async void OnDisappearing()
    {
        base.OnDisappearing();
        await _viewModel.OnDisappearingAsync();
    }
}